# -*- coding: utf-8 -*-
"""Slice diagnostics for the 2m BB20 wick -> BB4 RR2 candidate.

This script does not introduce a new entry engine. It reads the fixed 1:2 RR
trades generated by script 105 and searches simple, NinjaScript-friendly
filters such as direction, session, entry hour, risk bucket, fill speed, and
breakout candle close-position bucket.

Purpose:
- Keep the 1:2 RR structure intact.
- Find interpretable filters that may explain why 2026 works while older
  years fail.
- Produce a ranked report without using future monthly regime selection.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import math
import sys
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
RR2_SCRIPT = SCRIPT_DIR / "105_2m_bb20_wick_bb4_rr2.py"
SOURCE_DIR = ROOT / "result" / "bb20_wick_bb4_rr2_2m_20230101_20260617"
OUTPUT_DIR = ROOT / "result" / "bb20_wick_rr2_slice_diagnostics"
TEST_START = "2023-01-01"
TEST_END = "2026-06-17"


spec = importlib.util.spec_from_file_location("rr2_105", RR2_SCRIPT)
rr2 = importlib.util.module_from_spec(spec)
sys.modules["rr2_105"] = rr2
assert spec.loader is not None
spec.loader.exec_module(rr2)


def quiet_call(fn, *args, **kwargs):
    with contextlib.redirect_stdout(io.StringIO()):
        return fn(*args, **kwargs)


def profit_factor(values: pd.Series) -> float:
    vals = pd.to_numeric(values, errors="coerce").fillna(0.0)
    gp = vals[vals > 0].sum()
    gl = abs(vals[vals < 0].sum())
    if gl == 0:
        return math.inf if gp > 0 else 0.0
    return float(gp / gl)


def max_drawdown(values: pd.Series) -> float:
    vals = pd.to_numeric(values, errors="coerce").fillna(0.0)
    eq = vals.cumsum()
    dd = eq.cummax() - eq
    return float(dd.max()) if len(vals) else 0.0


def round_floats(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in out.columns:
        if pd.api.types.is_float_dtype(out[col]):
            out[col] = out[col].round(4)
    return out


def load_trades() -> tuple[pd.DataFrame, int]:
    trades_path = SOURCE_DIR / "bb20_wick_bb4_rr2_trades.csv"
    entries_path = SOURCE_DIR / "bb20_wick_bb4_rr2_entries.csv"
    if not trades_path.exists() or not entries_path.exists():
        raise FileNotFoundError("Run script 105 for TEST_START=2023-01-01 TEST_END=2026-06-17 first.")

    trades = pd.read_csv(trades_path)
    entries = pd.read_csv(entries_path)
    trades["entry_time"] = pd.to_datetime(trades["entry_time"])
    trades["exit_time"] = pd.to_datetime(trades["exit_time"])
    entries["entry_time"] = pd.to_datetime(entries["entry_time"])

    merge_cols = ["entry_time", "direction", "entry_price"]
    keep = merge_cols + ["breakout_close_position", "breakout_time"]
    enriched = trades.merge(entries[keep], on=merge_cols, how="left")
    enriched["hour"] = enriched["entry_time"].dt.hour
    enriched["weekday"] = enriched["entry_time"].dt.day_name()
    enriched["risk_bucket"] = pd.cut(
        enriched["risk_points"],
        bins=[0.0, 2.0, 3.0, 4.0, 6.0, 99.0],
        labels=["risk_0_2", "risk_2_3", "risk_3_4", "risk_4_6", "risk_6p"],
        include_lowest=True,
    ).astype(str)
    enriched["fill_bucket"] = pd.cut(
        enriched["bars_to_fill"],
        bins=[0, 1, 3, 6, 10, 20],
        labels=["fill_1", "fill_2_3", "fill_4_6", "fill_7_10", "fill_11_20"],
        include_lowest=True,
    ).astype(str)
    enriched["closepos_bucket"] = pd.cut(
        enriched["breakout_close_position"],
        bins=[-0.01, 0.25, 0.50, 0.75, 1.01],
        labels=["closepos_0_25", "closepos_25_50", "closepos_50_75", "closepos_75_100"],
    ).astype(str)

    full = quiet_call(rr2.entry103.load_full_data)
    start = pd.Timestamp(TEST_START, tz="Asia/Seoul")
    end = pd.Timestamp(TEST_END, tz="Asia/Seoul")
    df = full[(full.index >= start) & (full.index < end)].copy()
    trading_days = int(pd.Series(df.index.date).nunique())
    return enriched, trading_days


def summarize(group: pd.DataFrame, trading_days: int) -> dict:
    pnl = group["net_points"].astype(float)
    yearly = group.groupby("year")["net_points"].sum()
    monthly = group.groupby("month")["net_points"].sum()
    return {
        "trades": int(len(group)),
        "trading_days": int(trading_days),
        "active_days": int(group["day"].nunique()) if len(group) else 0,
        "trades_per_day": float(len(group) / trading_days) if trading_days else 0.0,
        "trades_per_active_day": float(len(group) / group["day"].nunique()) if group["day"].nunique() else 0.0,
        "net_points": float(pnl.sum()),
        "avg_points": float(pnl.mean()) if len(group) else 0.0,
        "profit_factor": profit_factor(pnl),
        "win_rate": float((pnl > 0).mean() * 100) if len(group) else 0.0,
        "target_rate": float((group["exit_reason"] == "target_2r").mean() * 100) if len(group) else 0.0,
        "max_drawdown_points": max_drawdown(pnl),
        "positive_years": int((yearly > 0).sum()),
        "years": int(yearly.size),
        "positive_month_rate": float((monthly > 0).mean() * 100) if monthly.size else 0.0,
        "avg_risk": float(group["risk_points"].mean()) if len(group) else 0.0,
        "avg_hold_bars": float(group["hold_bars"].mean()) if len(group) else 0.0,
    }


def filter_label(cols: list[str], key) -> str:
    if not isinstance(key, tuple):
        key = (key,)
    return " & ".join("%s=%s" % (col, value) for col, value in zip(cols, key))


def slice_table(trades: pd.DataFrame, cols: list[str], trading_days: int) -> pd.DataFrame:
    rows = []
    for key, group in trades.groupby(cols, dropna=False, sort=True):
        row = {
            "slice_type": "+".join(cols),
            "slice": filter_label(cols, key),
        }
        row.update(summarize(group, trading_days))
        rows.append(row)
    return pd.DataFrame(rows)


def build_diagnostics(trades: pd.DataFrame, trading_days: int) -> pd.DataFrame:
    parts = [pd.DataFrame([{"slice_type": "all", "slice": "all", **summarize(trades, trading_days)}])]
    for cols in [
        ["direction"],
        ["session"],
        ["hour"],
        ["weekday"],
        ["risk_bucket"],
        ["fill_bucket"],
        ["closepos_bucket"],
        ["direction", "session"],
        ["direction", "hour"],
        ["session", "hour"],
        ["direction", "risk_bucket"],
        ["direction", "fill_bucket"],
        ["direction", "closepos_bucket"],
    ]:
        parts.append(slice_table(trades, cols, trading_days))
    out = pd.concat(parts, ignore_index=True)
    out["target_frequency"] = out["trades_per_day"].between(10.0, 20.0)
    out["positive_all_years"] = out["positive_years"] == out["years"]
    out["score"] = (
        out["net_points"]
        - out["max_drawdown_points"] * 0.25
        + out["positive_month_rate"] * 5.0
        + out["target_frequency"].astype(int) * 500.0
    )
    return round_floats(out.sort_values(["target_frequency", "net_points"], ascending=[False, False]))


def grouped_report(trades: pd.DataFrame, cols: list[str], trading_days: int) -> pd.DataFrame:
    rows = []
    for key, group in trades.groupby(cols, sort=True):
        if not isinstance(key, tuple):
            key = (key,)
        row = dict(zip(cols, key))
        row.update(summarize(group, trading_days))
        rows.append(row)
    return round_floats(pd.DataFrame(rows))


def table_html(df: pd.DataFrame, title: str, max_rows: int | None = None) -> str:
    show = df.head(max_rows).copy() if max_rows else df.copy()
    headers = "".join("<th>%s</th>" % c for c in show.columns)
    rows = []
    for _, row in show.iterrows():
        cells = []
        for col, value in row.items():
            cls = ""
            if col in {"net_points", "avg_points", "profit_factor", "score"}:
                try:
                    num = float(value)
                    cls = "pos" if (num >= 1 if col == "profit_factor" else num > 0) else "neg"
                except Exception:
                    pass
            text = "" if pd.isna(value) else ("%.4f" % value if isinstance(value, float) else str(value))
            cells.append("<td class='%s'>%s</td>" % (cls, text))
        rows.append("<tr>%s</tr>" % "".join(cells))
    return "<section><h2>%s</h2><div><table><thead><tr>%s</tr></thead><tbody>%s</tbody></table></div></section>" % (
        title,
        headers,
        "".join(rows),
    )


def write_html(diagnostics: pd.DataFrame, yearly: pd.DataFrame, monthly: pd.DataFrame) -> None:
    css = """
    body{margin:0;font-family:Arial,'Malgun Gothic',sans-serif;background:#f7f8fb;color:#17202a}
    header{background:#101820;color:#fff;padding:30px 42px}h1{font-size:26px;margin:0 0 8px}p{margin:0;color:#c9d3df}
    main{max-width:1900px;margin:0 auto;padding:24px 42px 48px}section{background:#fff;border:1px solid #d9dee7;border-radius:8px;padding:18px;margin:16px 0}
    h2{font-size:18px;margin:0 0 10px}div{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:13px}
    th,td{padding:7px 9px;border-bottom:1px solid #d9dee7;text-align:right;white-space:nowrap}th{background:#eef2f7}
    td:first-child,th:first-child,td:nth-child(2),th:nth-child(2){text-align:left}.pos{color:#087f5b;font-weight:700;background:#e6f4ee}.neg{color:#c92a2a;font-weight:700;background:#fff0f0}
    """
    html = """<!doctype html><html lang='ko'><head><meta charset='utf-8'><title>2m RR2 Slice Diagnostics</title><style>%s</style></head>
<body><header><h1>2m BB20 Wick BB4 RR2 Slice Diagnostics</h1><p>Simple filters only: direction, session, hour, weekday, risk, fill speed, and breakout close-position.</p></header><main>
%s%s%s
</main></body></html>""" % (
        css,
        table_html(diagnostics.sort_values("score", ascending=False), "Ranked Slices", 160),
        table_html(yearly, "Yearly Baseline"),
        table_html(monthly, "Monthly Baseline"),
    )
    (OUTPUT_DIR / "rr2_slice_diagnostics_report.html").write_text(html, encoding="utf-8")


def run():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    trades, trading_days = load_trades()
    diagnostics = build_diagnostics(trades, trading_days)
    yearly = grouped_report(trades, ["year"], trading_days)
    monthly = grouped_report(trades, ["month"], trading_days)

    trades.to_csv(OUTPUT_DIR / "rr2_slice_enriched_trades.csv", index=False, encoding="utf-8-sig")
    diagnostics.to_csv(OUTPUT_DIR / "rr2_slice_diagnostics.csv", index=False, encoding="utf-8-sig")
    yearly.to_csv(OUTPUT_DIR / "rr2_slice_yearly_baseline.csv", index=False, encoding="utf-8-sig")
    monthly.to_csv(OUTPUT_DIR / "rr2_slice_monthly_baseline.csv", index=False, encoding="utf-8-sig")
    write_html(diagnostics, yearly, monthly)

    print("=== 2M BB20 WICK BB4 RR2 SLICE DIAGNOSTICS ===")
    print("Trading days:", trading_days)
    print(diagnostics.head(40).to_string(index=False))
    print("WROTE:", OUTPUT_DIR)


if __name__ == "__main__":
    run()
