# -*- coding: utf-8 -*-
"""Regime diagnostics for the closest 2m session-liquidity RR2 candidate.

The input is the selected target-frequency trade file generated by script 115.
This script adds pre-entry daily/monthly regime features and checks whether
simple thresholds can preserve 10-20 trades/day while improving expectancy.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import math
import sys
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
BASE_SCRIPT = SCRIPT_DIR / "100_strategy2_grid_multitimeframe_month_filter.py"
INPUT = ROOT / "result" / "session_liquidity_rr2_sweep" / "session_liquidity_rr2_best_trades.csv"
OUTPUT_DIR = ROOT / "result" / "session_liquidity_rr2_regime_diagnostics"
TRADING_DAYS = 1075
TRADING_DAYS_2026 = 142


spec = importlib.util.spec_from_file_location("base100_for_117", BASE_SCRIPT)
base = importlib.util.module_from_spec(spec)
sys.modules["base100_for_117"] = base
assert spec.loader is not None
spec.loader.exec_module(base)


def quiet_call(fn, *args, **kwargs):
    with contextlib.redirect_stdout(io.StringIO()):
        return fn(*args, **kwargs)


def profit_factor(values: pd.Series) -> float:
    vals = pd.to_numeric(values, errors="coerce").fillna(0.0)
    gp = vals[vals > 0].sum()
    gl = abs(vals[vals < 0].sum())
    if gl == 0:
        return math.inf if gp > 0 else 0.0
    return float(gp / gl)


def max_drawdown(values: pd.Series) -> float:
    vals = pd.to_numeric(values, errors="coerce").fillna(0.0)
    eq = vals.cumsum()
    dd = eq.cummax() - eq
    return float(dd.max()) if len(vals) else 0.0


def summarize(trades: pd.DataFrame, trading_days: int, label: str) -> dict:
    pnl = trades["net_points"].astype(float) if len(trades) else pd.Series(dtype=float)
    monthly = trades.groupby("month")["net_points"].sum() if len(trades) else pd.Series(dtype=float)
    return {
        "filter": label,
        "trades": int(len(trades)),
        "active_days": int(trades["day"].nunique()) if len(trades) else 0,
        "trades_per_day": float(len(trades) / trading_days) if trading_days else 0.0,
        "trades_per_active_day": float(len(trades) / trades["day"].nunique()) if len(trades) and trades["day"].nunique() else 0.0,
        "net_points": float(pnl.sum()) if len(pnl) else 0.0,
        "avg_points": float(pnl.mean()) if len(pnl) else 0.0,
        "profit_factor": profit_factor(pnl),
        "win_rate": float((pnl > 0).mean() * 100) if len(pnl) else 0.0,
        "target_rate": float((trades["exit_reason"] == "target_2r").mean() * 100) if len(trades) else 0.0,
        "max_drawdown_points": max_drawdown(pnl),
        "positive_month_rate": float((monthly > 0).mean() * 100) if len(monthly) else 0.0,
    }


def round_floats(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in out.columns:
        if pd.api.types.is_float_dtype(out[col]):
            out[col] = out[col].round(4)
    return out


def daily_regime_features() -> pd.DataFrame:
    df = quiet_call(base.load_tf, "2m").copy()
    daily = df.resample("1D").agg(open=("open", "first"), high=("high", "max"), low=("low", "min"), close=("close", "last"))
    daily = daily.dropna().copy()
    daily["day"] = [ts.date().isoformat() for ts in daily.index]
    daily["range"] = daily["high"] - daily["low"]
    daily["ret1"] = daily["close"].pct_change()
    daily["ret20"] = daily["close"].pct_change(20)
    daily["ret60"] = daily["close"].pct_change(60)
    daily["adr20"] = daily["range"].rolling(20, min_periods=20).mean()
    daily["adr60"] = daily["range"].rolling(60, min_periods=60).mean()
    daily["vol20"] = daily["ret1"].rolling(20, min_periods=20).std()
    daily["sma20"] = daily["close"].rolling(20, min_periods=20).mean()
    daily["sma60"] = daily["close"].rolling(60, min_periods=60).mean()
    daily["sma20_gt_sma60"] = daily["sma20"] > daily["sma60"]
    feature_cols = ["day", "close", "ret20", "ret60", "adr20", "adr60", "vol20", "sma20_gt_sma60"]
    shifted = daily[feature_cols].copy()
    shifted[feature_cols[1:]] = shifted[feature_cols[1:]].shift(1)
    return shifted


def monthly_regime_features() -> pd.DataFrame:
    df = quiet_call(base.load_tf, "2m").copy()
    monthly = df.resample("ME").agg(close=("close", "last"), high=("high", "max"), low=("low", "min"))
    monthly = monthly.dropna().copy()
    monthly["month"] = monthly.index.strftime("%Y-%m")
    monthly["monthly_ret"] = monthly["close"].pct_change()
    monthly["monthly_range"] = monthly["high"] - monthly["low"]
    monthly["prev_month_ret"] = monthly["monthly_ret"].shift(1)
    monthly["prev_month_range"] = monthly["monthly_range"].shift(1)
    monthly["prev_month_close"] = monthly["close"].shift(1)
    return monthly[["month", "prev_month_ret", "prev_month_range", "prev_month_close"]]


def add_regimes(trades: pd.DataFrame) -> pd.DataFrame:
    out = trades.copy()
    out["entry_time"] = pd.to_datetime(out["entry_time"])
    out["day"] = out["day"].astype(str)
    out["month"] = out["month"].astype(str)
    out = out.merge(daily_regime_features(), on="day", how="left")
    out = out.merge(monthly_regime_features(), on="month", how="left")
    return out


def candidate_masks(df: pd.DataFrame) -> list[tuple[str, pd.Series]]:
    candidates: list[tuple[str, pd.Series]] = [("baseline", pd.Series(True, index=df.index))]
    feature_thresholds = {
        "ret20": [-0.04, -0.02, 0.0, 0.02, 0.04],
        "ret60": [-0.08, -0.04, 0.0, 0.04, 0.08],
        "adr20": [20.0, 30.0, 40.0, 50.0],
        "adr60": [20.0, 30.0, 40.0, 50.0],
        "vol20": [0.006, 0.008, 0.010, 0.012],
        "prev_month_ret": [-0.04, -0.02, 0.0, 0.02, 0.04],
        "prev_month_range": [80.0, 120.0, 160.0, 220.0],
        "prev_month_close": [1900.0, 2200.0, 2600.0, 3000.0, 3400.0],
    }
    for col, thresholds in feature_thresholds.items():
        vals = pd.to_numeric(df[col], errors="coerce")
        for threshold in thresholds:
            candidates.append((f"{col} >= {threshold:.4f}", vals >= threshold))
            candidates.append((f"{col} <= {threshold:.4f}", vals <= threshold))
    for value in [True, False]:
        candidates.append((f"sma20_gt_sma60 == {value}", df["sma20_gt_sma60"] == value))

    # Two-way broad combinations that remain easy to implement in NinjaScript.
    for ret_threshold in [0.0, 0.02]:
        for adr_threshold in [30.0, 40.0]:
            candidates.append((
                f"prev_month_ret >= {ret_threshold:.2f} & adr60 >= {adr_threshold:.1f}",
                (pd.to_numeric(df["prev_month_ret"], errors="coerce") >= ret_threshold)
                & (pd.to_numeric(df["adr60"], errors="coerce") >= adr_threshold),
            ))
            candidates.append((
                f"ret60 >= {ret_threshold:.2f} & adr20 >= {adr_threshold:.1f}",
                (pd.to_numeric(df["ret60"], errors="coerce") >= ret_threshold)
                & (pd.to_numeric(df["adr20"], errors="coerce") >= adr_threshold),
            ))
    return candidates


def table_html(df: pd.DataFrame, title: str, max_rows: int | None = None) -> str:
    show = df.head(max_rows).copy() if max_rows else df.copy()
    headers = "".join("<th>%s</th>" % c for c in show.columns)
    rows = []
    for _, row in show.iterrows():
        cells = []
        for col, value in row.items():
            cls = ""
            if col in {"net_points", "profit_factor", "score", "sample2026_net_points", "sample2026_profit_factor"}:
                try:
                    num = float(value)
                    cls = "pos" if (num >= 1 if "profit_factor" in col else num > 0) else "neg"
                except Exception:
                    pass
            text = "" if pd.isna(value) else ("%.4f" % value if isinstance(value, float) else str(value))
            cells.append("<td class='%s'>%s</td>" % (cls, text))
        rows.append("<tr>%s</tr>" % "".join(cells))
    return "<section><h2>%s</h2><div><table><thead><tr>%s</tr></thead><tbody>%s</tbody></table></div></section>" % (
        title,
        headers,
        "".join(rows),
    )


def write_html(results: pd.DataFrame) -> None:
    css = """
    body{margin:0;font-family:Arial,'Malgun Gothic',sans-serif;background:#f7f8fb;color:#17202a}
    header{background:#283618;color:#fff;padding:30px 42px}h1{font-size:26px;margin:0 0 8px}p{margin:0;color:#e9edc9}
    main{max-width:1800px;margin:0 auto;padding:24px 42px 48px}section{background:#fff;border:1px solid #d9dee7;border-radius:8px;padding:18px;margin:16px 0}
    h2{font-size:18px;margin:0 0 10px}div{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:13px}
    th,td{padding:7px 9px;border-bottom:1px solid #d9dee7;text-align:right;white-space:nowrap}th{background:#eef2f7}
    td:first-child,th:first-child{text-align:left}.pos{color:#087f5b;font-weight:700;background:#e6f4ee}.neg{color:#c92a2a;font-weight:700;background:#fff0f0}
    """
    target = results[results["target_frequency"]].sort_values("net_points", ascending=False)
    html = """<!doctype html><html lang='ko'><head><meta charset='utf-8'><title>Session Liquidity RR2 Regime Diagnostics</title><style>%s</style></head>
<body><header><h1>Session Liquidity RR2 Regime Diagnostics</h1><p>Daily/monthly pre-entry regime filters for the closest fixed 1:2 target-frequency candidate.</p></header><main>
%s%s
</main></body></html>""" % (
        css,
        table_html(target, "Regime Filters Within 10-20 Trades/Day", 160),
        table_html(results.sort_values("score", ascending=False), "All Regime Filters Ranked", 260),
    )
    (OUTPUT_DIR / "session_liquidity_rr2_regime_diagnostics_report.html").write_text(html, encoding="utf-8")


def run() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    trades = add_regimes(pd.read_csv(INPUT))
    sample2026 = trades[trades["entry_time"] >= pd.Timestamp("2026-01-01", tz=trades["entry_time"].dt.tz)]
    rows = []
    for label, mask in candidate_masks(trades):
        subset = trades[mask].copy()
        if subset.empty:
            continue
        sample_subset = sample2026[mask.loc[sample2026.index]].copy()
        row = summarize(subset, TRADING_DAYS, label)
        sample_row = summarize(sample_subset, TRADING_DAYS_2026, label)
        row["sample2026_trades"] = sample_row["trades"]
        row["sample2026_trades_per_day"] = sample_row["trades_per_day"]
        row["sample2026_net_points"] = sample_row["net_points"]
        row["sample2026_profit_factor"] = sample_row["profit_factor"]
        row["sample2026_target_rate"] = sample_row["target_rate"]
        row["target_frequency"] = 10.0 <= row["trades_per_day"] <= 20.0
        row["sample2026_target_frequency"] = 10.0 <= row["sample2026_trades_per_day"] <= 20.0
        row["score"] = (
            row["net_points"]
            - row["max_drawdown_points"] * 0.20
            + row["positive_month_rate"] * 5.0
            + (1000.0 if row["target_frequency"] else 0.0)
            + row["sample2026_net_points"] * 0.10
        )
        rows.append(row)
    results = round_floats(pd.DataFrame(rows).sort_values(["target_frequency", "net_points"], ascending=[False, False]))
    results.to_csv(OUTPUT_DIR / "session_liquidity_rr2_regime_diagnostics.csv", index=False, encoding="utf-8-sig")
    write_html(results)
    print("=== SESSION LIQUIDITY RR2 REGIME DIAGNOSTICS ===")
    print("Input trades:", len(trades), "Candidates:", len(results))
    print(results.head(80).to_string(index=False))
    print("WROTE:", OUTPUT_DIR)


if __name__ == "__main__":
    run()
